package daemon

import (
	"fmt"
	"log"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/aynaash/nextdeploy/shared/caddy"
	"github.com/aynaash/nextdeploy/shared/config"
	"github.com/aynaash/nextdeploy/shared/nextcore"
)

const mainCaddyfilePath = "/etc/caddy/Caddyfile"

// sanitizeAppName bounds what can become a fragment filename. appName flows into
// filepath.Join(configDir, appName+".caddy"); without this guard a value like
// "../../etc/cron.d/x" would let a fragment escape the import directory.
//
// It delegates to the shared rule rather than carrying its own regex. The old
// local pattern (`^[a-zA-Z0-9_-]+$`) accepted uppercase and underscores that
// validateAppName rejects — two opinions about one field is how a name ends up
// valid in one layer and fatal in the next.
func sanitizeAppName(appName string) error {
	return config.ValidateAppName(appName)
}

// siteAddrs extracts the site-address tokens a fragment declares — everything
// before the first "{". Deliberately a dumb text scan rather than a Caddyfile
// parser: it only needs the addresses, and the fragments are generated by
// shared/caddy so the format stays simple. It does NOT understand matchers or
// multi-line site addresses; keep GenerateCaddyfile's output single-line-header
// or this stops seeing collisions.
func siteAddrs(fragment []byte) []string {
	head := string(fragment)
	if i := strings.IndexByte(head, '{'); i >= 0 {
		head = head[:i]
	}
	var out []string
	for _, tok := range strings.FieldsFunc(head, func(r rune) bool {
		return r == ',' || r == ' ' || r == '\n' || r == '\t' || r == '\r'
	}) {
		if tok != "" {
			out = append(out, tok)
		}
	}
	return out
}

// fragmentsClaiming returns the app names (excluding self) whose fragment
// declares any of addrs. This is the information the operator needs and the
// daemon already has — without it, a collision surfaces only as raw Caddy JSON
// and a grep hunt on the server.
func (cm *CaddyManager) fragmentsClaiming(addrs []string, self string) ([]string, error) {
	want := make(map[string]bool, len(addrs))
	for _, a := range addrs {
		want[a] = true
	}
	entries, err := os.ReadDir(cm.configDir)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, fmt.Errorf("failed to read caddy fragment dir: %w", err)
	}
	var claiming []string
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".caddy") {
			continue
		}
		if e.Name() == self+".caddy" {
			continue // our own fragment — overwriting it is the expected case
		}
		data, rerr := os.ReadFile(filepath.Join(cm.configDir, e.Name())) // #nosec G304 — path built from a validated dir entry
		if rerr != nil {
			continue
		}
		for _, a := range siteAddrs(data) {
			if want[a] {
				claiming = append(claiming, strings.TrimSuffix(e.Name(), ".caddy"))
				break
			}
		}
	}
	return claiming, nil
}

// supersedeConflicts removes any OTHER app's fragment claiming one of addrs and
// returns the app names it removed, so the caller can shout about it.
//
// Policy note: re-deploying an existing site under a new app name is the common
// case, so superseding beats refusing on ergonomics. But it DELETES another
// app's routing — which is why it is never silent, and why the log points at
// `destroy` to clean up the superseded app's service and port.
func (cm *CaddyManager) supersedeConflicts(appName string, addrs []string) ([]string, error) {
	claiming, err := cm.fragmentsClaiming(addrs, appName)
	if err != nil {
		return nil, err
	}
	var superseded []string
	for _, other := range claiming {
		path := filepath.Join(cm.configDir, other+".caddy")
		if rmErr := os.Remove(path); rmErr != nil && !os.IsNotExist(rmErr) {
			return superseded, fmt.Errorf("failed to remove stale caddy fragment %s claiming %v: %w", path, addrs, rmErr)
		}
		superseded = append(superseded, other)
	}
	return superseded, nil
}

type CaddyManager struct {
	configDir string
}

func NewCaddyManager() *CaddyManager {
	dir := "/etc/caddy/nextdeploy.d"
	// #nosec G:u301
	_ = os.MkdirAll(dir, 0755)
	_ = os.Chmod(dir, 0755)
	return &CaddyManager{
		configDir: dir,
	}
}

func (cm *CaddyManager) GenerateConfig(appName, domain, outputMode string, port int, appDir string, features *nextcore.DetectedFeatures, distDir, exportDir string) error {
	if err := sanitizeAppName(appName); err != nil {
		return err
	}
	caddyConfig := caddy.GenerateCaddyfile(appName, domain, outputMode, port, appDir, features, distDir, exportDir)

	// Fragments are keyed by app name, but Caddy routes on the SITE ADDRESS —
	// and a site address may only appear in one block. Shipping the same domain
	// under a new app name therefore leaves the old fragment claiming it, and
	// the combined config fails to adapt with "ambiguous site definition". App
	// name is our primary key; the domain is Caddy's. Reconcile before commit.
	superseded, err := cm.supersedeConflicts(appName, siteAddrs([]byte(caddyConfig)))
	if err != nil {
		return err
	}
	for _, old := range superseded {
		log.Printf("[caddy] WARNING: app %q now owns a domain previously served by app %q — "+
			"removed stale fragment %s.caddy. If %q is still running, run "+
			"`nextdeploy destroy --appName=%s` to free its service and port.",
			appName, old, old, old, old)
	}

	if err := cm.commitFragmentSafely(appName, []byte(caddyConfig)); err != nil {
		return err
	}
	log.Printf("Caddy config generated for %s at %s", appName, filepath.Join(cm.configDir, appName+".caddy"))
	return nil
}

// commitFragmentSafely validates the *resulting* Caddy configuration in a
// sandbox before the fragment is allowed to touch the live import directory.
// Previously a malformed fragment was written straight into configDir and only
// caught by the post-write Validate() — by which point the broken file was
// already live and would also poison the next reload of every other app. Here:
//
//  1. mirror the current live fragments into a temp dir,
//  2. drop in the candidate fragment (replacing this app's, if any),
//  3. validate a candidate main Caddyfile whose import points at the temp dir,
//  4. only on success, atomically rename the fragment into the live dir.
func (cm *CaddyManager) commitFragmentSafely(appName string, content []byte) error {
	sandbox, err := os.MkdirTemp("", "nextdeploy-caddy-*")
	if err != nil {
		return fmt.Errorf("failed to provision caddy validation sandbox: %w", err)
	}
	defer os.RemoveAll(sandbox)

	// Mirror existing live fragments so cross-fragment references and the full
	// import set are validated as a whole, not the candidate in isolation.
	if entries, err := os.ReadDir(cm.configDir); err == nil {
		for _, e := range entries {
			if e.IsDir() || !strings.HasSuffix(e.Name(), ".caddy") {
				continue
			}
			data, rerr := os.ReadFile(filepath.Join(cm.configDir, e.Name()))
			if rerr != nil {
				continue
			}
			// #nosec G306
			_ = os.WriteFile(filepath.Join(sandbox, e.Name()), data, 0644)
		}
	}

	// Drop in (or overwrite) the candidate fragment.
	// #nosec G306
	if err := os.WriteFile(filepath.Join(sandbox, appName+".caddy"), content, 0644); err != nil {
		return fmt.Errorf("failed to stage candidate caddy fragment: %w", err)
	}

	// Build a candidate main Caddyfile that imports the sandbox instead of the
	// live dir, reusing the real global options (e.g. coraza ordering) so the
	// validation matches what reload will actually parse.
	candidateMain := filepath.Join(sandbox, "Caddyfile")
	var mainContent string
	if existing, err := os.ReadFile(mainCaddyfilePath); err == nil {
		mainContent = strings.ReplaceAll(string(existing), cm.configDir, sandbox)
	} else {
		mainContent = fmt.Sprintf("import %s/*.caddy\n", sandbox)
	}
	// #nosec G306
	if err := os.WriteFile(candidateMain, []byte(mainContent), 0644); err != nil {
		return fmt.Errorf("failed to stage candidate Caddyfile: %w", err)
	}

	caddyPath := resolveTool("caddy")
	// #nosec G204
	cmd := exec.Command(caddyPath, "validate", "--config", candidateMain, "--adapter", "caddyfile")
	if out, err := cmd.CombinedOutput(); err != nil {
		// Name the conflicting app rather than handing back raw Caddy JSON for
		// the operator to decode. supersedeConflicts should have cleared these
		// already, so a hit here means a genuine multi-app-one-domain misconfig
		// (or a fragment siteAddrs couldn't parse) — exactly the case a human
		// should resolve.
		addrs := siteAddrs(content)
		if conflicts, cerr := cm.fragmentsClaiming(addrs, appName); cerr == nil && len(conflicts) > 0 {
			return fmt.Errorf(
				"caddy fragment for %q not committed: site address(es) %v are already served by app(s) %v — "+
					"run `nextdeploy destroy --appName=<that-app>` to release the domain, or give this app a different domain (caddy said: %s)",
				appName, addrs, conflicts, strings.TrimSpace(string(out)))
		}
		return fmt.Errorf("caddy pre-flight validation failed for %s (fragment not committed): %w - %s", appName, err, string(out))
	}

	// Validation passed — atomically install the fragment. CreateTemp in the
	// live dir keeps the temp file on the same filesystem so the rename is a
	// true atomic swap (no half-written file is ever visible to a reload).
	finalPath := filepath.Join(cm.configDir, appName+".caddy")
	tmp, err := os.CreateTemp(cm.configDir, "."+appName+".caddy.*")
	if err != nil {
		return fmt.Errorf("failed to create temp caddy fragment: %w", err)
	}
	tmpPath := tmp.Name()
	if _, err := tmp.Write(content); err != nil {
		_ = tmp.Close()
		_ = os.Remove(tmpPath)
		return fmt.Errorf("failed to write temp caddy fragment: %w", err)
	}
	if err := tmp.Close(); err != nil {
		_ = os.Remove(tmpPath)
		return fmt.Errorf("failed to close temp caddy fragment: %w", err)
	}
	// #nosec G302
	_ = os.Chmod(tmpPath, 0644)
	if err := os.Rename(tmpPath, finalPath); err != nil {
		_ = os.Remove(tmpPath)
		return fmt.Errorf("failed to commit validated caddy fragment for %s: %w", appName, err)
	}
	return nil
}

func (cm *CaddyManager) EnsureMainCaddyfile() error {
	importDirective := fmt.Sprintf("import %s/*.caddy\n", cm.configDir)
	corazaGlobal := "{\n\torder coraza_waf first\n}\n\n"

	content, err := os.ReadFile(mainCaddyfilePath)
	if err != nil {
		if os.IsNotExist(err) {
			return os.WriteFile(mainCaddyfilePath, []byte(corazaGlobal+importDirective), 0600)
		}
		return fmt.Errorf("failed to read main Caddyfile: %w", err)
	}

	contentStr := string(content)

	// Surgically remove the default :80 block if it exists (Welcome to Caddy page)
	if strings.Contains(contentStr, ":80 {") && strings.Contains(contentStr, "root * /usr/share/caddy") {
		// This is a naive but effective way to strip the default block for common Caddy installs
		lines := strings.Split(contentStr, "\n")
		var newLines []string
		inDefaultBlock := false
		for _, line := range lines {
			trimmed := strings.TrimSpace(line)
			if trimmed == ":80 {" {
				inDefaultBlock = true
				continue
			}
			if inDefaultBlock {
				if trimmed == "}" {
					inDefaultBlock = false
				}
				continue
			}
			newLines = append(newLines, line)
		}
		contentStr = strings.Join(newLines, "\n")
	}

	newContent := contentStr

	// Ensure global options block is at the top
	if !strings.Contains(newContent, "order coraza_waf") {
		newContent = corazaGlobal + newContent
	}

	// Ensure import directive is present
	if !strings.Contains(newContent, importDirective) {
		if len(newContent) > 0 && newContent[len(newContent)-1] != '\n' {
			newContent += "\n"
		}
		newContent += importDirective
	}

	if newContent != string(content) {
		if err := os.WriteFile(mainCaddyfilePath, []byte(newContent), 0600); err != nil {
			return fmt.Errorf("failed to update main Caddyfile: %w", err)
		}
	}

	return nil
}

func (cm *CaddyManager) Reload() error {
	// Validate config before attempting reload to prevent broken configs
	if err := cm.Validate(); err != nil {
		return fmt.Errorf("config validation failed before reload: %w", err)
	}

	systemctl := resolveTool("systemctl")
	// #nosec G204
	cmd := exec.Command(systemctl, "reload", "caddy")
	output, err := cmd.CombinedOutput()
	if err == nil {
		log.Println("Caddy reloaded successfully via systemctl.")
		return nil
	}

	log.Printf("Warning: systemctl reload caddy failed (%v), falling back to direct caddy reload...", err)
	caddyPath := resolveTool("caddy")
	// #nosec G204
	fallbackCmd := exec.Command(caddyPath, "reload", "--config", mainCaddyfilePath, "--adapter", "caddyfile")
	output, err = fallbackCmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("caddy reload failed (systemctl and fallback): %w - %s", err, string(output))
	}

	log.Println("Caddy reloaded successfully via direct fallback command.")
	return nil
}

func (cm *CaddyManager) Validate() error {
	caddyPath := resolveTool("caddy")
	// #nosec G204
	cmd := exec.Command(caddyPath, "validate", "--config", mainCaddyfilePath)
	output, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("caddy validation failed: %w - %s", err, string(output))
	}
	return nil
}

func (cm *CaddyManager) RemoveConfig(appName string) error {
	if err := sanitizeAppName(appName); err != nil {
		return err
	}
	configPath := filepath.Join(cm.configDir, fmt.Sprintf("%s.caddy", appName))
	if err := os.Remove(configPath); err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("failed to remove caddy config for %s: %w", appName, err)
	}
	return nil
}
