package nextcompile

import (
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"
)

type routeRegexCase struct {
	route      string
	wantRegex  string
	wantParams []string
	matchOK    []string
	matchFail  []string
}

func TestRouteToRegex(t *testing.T) {
	cases := []routeRegexCase{
		{
			route:      "/blog/[slug]",
			wantRegex:  `/^\/blog\/([^/]+)\/?$/`,
			wantParams: []string{"slug"},
			matchOK:    []string{"/blog/hello", "/blog/my-post/", "/blog/%20space"},
			matchFail:  []string{"/blog", "/blog/a/b", "/other/a"},
		},
		{
			route:      "/shop/[...path]",
			wantRegex:  `/^\/shop\/(.+?)\/?$/`,
			wantParams: []string{"path"},
			matchOK:    []string{"/shop/a", "/shop/a/b/c"},
			matchFail:  []string{"/shop", "/other"},
		},
		{
			route:      "/users/[id]/posts/[pid]",
			wantParams: []string{"id", "pid"},
			matchOK:    []string{"/users/42/posts/99"},
			matchFail:  []string{"/users/42", "/users/42/posts"},
		},
	}
	for _, tc := range cases {
		t.Run(tc.route, func(t *testing.T) { runRouteRegexCase(t, tc) })
	}
}

func runRouteRegexCase(t *testing.T, tc routeRegexCase) {
	t.Helper()
	got, params := routeToRegex(tc.route)
	if tc.wantRegex != "" && got != tc.wantRegex {
		t.Errorf("regex: got %s, want %s", got, tc.wantRegex)
	}
	if !stringSlicesEqual(params, tc.wantParams) {
		t.Errorf("params: got %v, want %v", params, tc.wantParams)
	}
	goPattern := strings.ReplaceAll(got[1:len(got)-1], `\/`, `/`)
	re := regexp.MustCompile(goPattern)
	assertMatches(t, re, goPattern, tc.matchOK, tc.matchFail)
}

func assertMatches(t *testing.T, re *regexp.Regexp, pattern string, ok, fail []string) {
	t.Helper()
	for _, v := range ok {
		if !re.MatchString(v) {
			t.Errorf("expected match for %q against %s", v, pattern)
		}
	}
	for _, v := range fail {
		if re.MatchString(v) {
			t.Errorf("expected no match for %q against %s", v, pattern)
		}
	}
}

func TestDynamicSpecificity(t *testing.T) {
	cases := []struct {
		a, b      string
		aMoreThan bool // a score > b score?
	}{
		{"/users/[id]/posts", "/users/[...rest]", true},
		{"/a/b/c", "/a/b/[x]", true},
		{"/docs/[[...slug]]", "/docs/[slug]", false},
	}
	for _, tc := range cases {
		sa, sb := dynamicSpecificity(tc.a), dynamicSpecificity(tc.b)
		if tc.aMoreThan && sa <= sb {
			t.Errorf("expected %q (score %d) > %q (score %d)", tc.a, sa, tc.b, sb)
		}
		if !tc.aMoreThan && sa >= sb {
			t.Errorf("expected %q (score %d) < %q (score %d)", tc.a, sa, tc.b, sb)
		}
	}
}

func TestRenderDispatchTable_StaticAndDynamic(t *testing.T) {
	refs := []ModuleRef{
		{RoutePath: "/", Kind: RouteKindPage, CompiledPath: ".next/server/app/page.js"},
		{RoutePath: "/api/users", Kind: RouteKindAPI, CompiledPath: ".next/server/app/api/users/route.js"},
		{RoutePath: "/blog/[slug]", Kind: RouteKindPage, CompiledPath: ".next/server/app/blog/[slug]/page.js"},
		{RoutePath: "/_middleware", Kind: RouteKindMiddleware, CompiledPath: ".next/server/middleware.js"},
	}
	src := renderDispatchTable(refs, nil, "../", ".next")

	// Must contain generated header.
	if !strings.Contains(src, "GENERATED BY nextcompile") {
		t.Error("missing header")
	}
	// Static routes in staticTable.
	if !strings.Contains(src, `"/": { kind: "page", usesRSC: false, hasActions: false, ppr: false,`) {
		t.Errorf("missing root entry:\n%s", src)
	}
	if !strings.Contains(src, `"/api/users": { kind: "api", usesRSC: false, hasActions: false, ppr: false,`) {
		t.Errorf("missing api entry:\n%s", src)
	}
	// Dynamic route in dynamicTable with compiled regex.
	if !strings.Contains(src, `"/blog/[slug]"`) || !strings.Contains(src, `pattern: /^\/blog\/`) {
		t.Errorf("missing dynamic entry:\n%s", src)
	}
	// Middleware ref.
	if !strings.Contains(src, `export const middlewareRef = { compiled:`) {
		t.Errorf("missing middlewareRef:\n%s", src)
	}
	// Import paths must go one level up (past _nextdeploy/).
	if !strings.Contains(src, `import("../.next/server/app/page.js")`) {
		t.Errorf("wrong import path:\n%s", src)
	}
}

func TestRenderDispatchTable_NoMiddleware(t *testing.T) {
	src := renderDispatchTable([]ModuleRef{
		{RoutePath: "/", Kind: RouteKindPage, CompiledPath: "server/app/page.js"},
	}, nil, "../", ".next")

	if !strings.Contains(src, "export const middlewareRef = null;") {
		t.Errorf("expected null middlewareRef:\n%s", src)
	}
}

// When OutDir is nested one level inside StandaloneDir (the cloudflare
// adapter's layout: <standalone>/.nextdeploy-cf/_nextdeploy/dispatch.mjs),
// dispatch.mjs has to walk back two levels to reach the standalone root,
// not one. This pins down that bug fix — see CF-deploy regression where
// esbuild errored with "Could not resolve "../.next/server/app/page.js"".
func TestEmitDispatchTable_NestedOutDirUsesDeeperImportPrefix(t *testing.T) {
	standalone := t.TempDir()
	outDir := filepath.Join(standalone, ".nextdeploy-cf")
	refs := []ModuleRef{
		{RoutePath: "/", Kind: RouteKindPage, CompiledPath: ".next/server/app/page.js"},
	}
	path, err := EmitDispatchTable(refs, nil, outDir, standalone, ".next")
	if err != nil {
		t.Fatalf("EmitDispatchTable: %v", err)
	}
	data, err := os.ReadFile(path) // #nosec G304
	if err != nil {
		t.Fatal(err)
	}
	got := string(data)
	if !strings.Contains(got, `import("../../.next/server/app/page.js")`) {
		t.Errorf("expected ../../ prefix for nested OutDir, got:\n%s", got)
	}
	if strings.Contains(got, `import("../.next/server/app/page.js")`) {
		t.Errorf("nested OutDir still emits single-../ prefix:\n%s", got)
	}
}

func TestImportPrefixFor(t *testing.T) {
	cases := []struct {
		name       string
		dispatch   string
		standalone string
		want       string
	}{
		{"sibling", "/x/_nextdeploy", "/x", "../"},
		{"one-level-nested", "/x/.nextdeploy-cf/_nextdeploy", "/x", "../../"},
		{"two-level-nested", "/x/a/b/_nextdeploy", "/x", "../../../"},
		{"empty-standalone", "/x/_nextdeploy", "", "../"},
	}
	for _, c := range cases {
		got := importPrefixFor(c.dispatch, c.standalone)
		if got != c.want {
			t.Errorf("%s: importPrefixFor(%q, %q) = %q, want %q", c.name, c.dispatch, c.standalone, got, c.want)
		}
	}
}

func TestEmitDispatchTable_WritesFile(t *testing.T) {
	dir := t.TempDir()
	refs := []ModuleRef{
		{RoutePath: "/", Kind: RouteKindPage, CompiledPath: "server/app/page.js"},
	}
	path, err := EmitDispatchTable(refs, nil, dir, "", ".next")
	if err != nil {
		t.Fatalf("EmitDispatchTable: %v", err)
	}
	if exp := filepath.Join(dir, "_nextdeploy", "dispatch.mjs"); path != exp {
		t.Errorf("path: got %s, want %s", path, exp)
	}
	data, err := os.ReadFile(path) // #nosec G304
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(data), "export const staticTable") {
		t.Errorf("file content:\n%s", data)
	}
}

// --- SSR M0: bootstrap chunks reach the dispatch table --------------------
//
// The scanner computes ModuleRef.BootstrapChunks, but the browser only ever
// sees them if renderEntryFields emits them. These pin that last hop: without
// it the chunk list is computed, discarded, and every page renders dead.

func TestRenderEntryFields_EmitsBootstrapChunks(t *testing.T) {
	r := ModuleRef{
		RoutePath:    "/",
		Kind:         RouteKindPage,
		CompiledPath: "server/app/page.js",
		UsesRSC:      true,
		BootstrapChunks: []string{
			"static/chunks/webpack-5adebf9f62dc3001.js",
			"static/chunks/main-app-da1490cb1b408188.js",
			"static/chunks/app/page-e1e2856be569970d.js",
		},
	}
	got := renderEntryFields(r, "../")
	want := `bootstrap: ["static/chunks/webpack-5adebf9f62dc3001.js", ` +
		`"static/chunks/main-app-da1490cb1b408188.js", ` +
		`"static/chunks/app/page-e1e2856be569970d.js"]`
	if !strings.Contains(got, want) {
		t.Errorf("entry fields missing bootstrap list.\ngot:  %s\nwant substring: %s", got, want)
	}
	// Chunks are client assets fetched by URL — emitting them as import()
	// thunks would drag the whole client graph into the Worker bundle.
	if strings.Contains(got, "import(\"../static/chunks") {
		t.Errorf("bootstrap chunks must not be emitted as imports:\n%s", got)
	}
}

func TestRenderEntryFields_BootstrapAbsentIsEmptyArray(t *testing.T) {
	// API routes and pages from a build with no app-build-manifest carry no
	// chunks. The field must still exist so the runtime can read entry.bootstrap
	// without an undefined guard at every call site.
	r := ModuleRef{
		RoutePath:    "/api/users",
		Kind:         RouteKindAPI,
		CompiledPath: "server/app/api/users/route.js",
	}
	if got := renderEntryFields(r, "../"); !strings.Contains(got, "bootstrap: []") {
		t.Errorf("want `bootstrap: []` for a chunkless entry, got:\n%s", got)
	}
}

func TestRenderDispatchTable_BootstrapInBothTables(t *testing.T) {
	refs := []ModuleRef{
		{
			RoutePath: "/", Kind: RouteKindPage, CompiledPath: "server/app/page.js",
			UsesRSC: true, BootstrapChunks: []string{"static/chunks/app/page-abc.js"},
		},
		{
			RoutePath: "/blog/[id]", Kind: RouteKindPage, CompiledPath: "server/app/blog/[id]/page.js",
			UsesRSC: true, BootstrapChunks: []string{"static/chunks/app/blog/[id]/page-def.js"},
		},
	}
	src := renderDispatchTable(refs, nil, "../", ".next")

	// Static table entry.
	if !strings.Contains(src, `bootstrap: ["static/chunks/app/page-abc.js"]`) {
		t.Errorf("static table lost its bootstrap chunks:\n%s", src)
	}
	// Dynamic table entry — a separate render path (renderEntryFields is
	// shared, but the dynamic branch builds its literal by hand).
	if !strings.Contains(src, `bootstrap: ["static/chunks/app/blog/[id]/page-def.js"]`) {
		t.Errorf("dynamic table lost its bootstrap chunks:\n%s", src)
	}
}

func TestRenderEntryFields_EmitsStylesheetsInCascadeOrder(t *testing.T) {
	r := ModuleRef{
		RoutePath:        "/",
		Kind:             RouteKindPage,
		CompiledPath:     "server/app/page.js",
		UsesRSC:          true,
		StylesheetChunks: []string{"static/css/root.css", "static/css/page.css"},
	}
	got := renderEntryFields(r, "../")
	if want := `css: ["static/css/root.css", "static/css/page.css"]`; !strings.Contains(got, want) {
		t.Errorf("entry fields missing css list.\ngot:  %s\nwant substring: %s", got, want)
	}
}

func TestRenderEntryFields_CSSAbsentIsEmptyArray(t *testing.T) {
	r := ModuleRef{RoutePath: "/", Kind: RouteKindPage, CompiledPath: "server/app/page.js"}
	if got := renderEntryFields(r, "../"); !strings.Contains(got, "css: []") {
		t.Errorf("want `css: []` for a page with no stylesheets, got:\n%s", got)
	}
}

func TestStringArrayLiteral(t *testing.T) {
	cases := []struct {
		name string
		in   []string
		want string
	}{
		{"nil", nil, "[]"},
		{"empty", []string{}, "[]"},
		{"one", []string{"a"}, `["a"]`},
		{"many", []string{"a", "b"}, `["a", "b"]`},
		{"escapes quotes", []string{`a"b`}, `["a\"b"]`},
		{"escapes backslash", []string{`a\b`}, `["a\\b"]`},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if got := stringArrayLiteral(tc.in); got != tc.want {
				t.Errorf("got %s, want %s", got, tc.want)
			}
		})
	}
}

func stringSlicesEqual(a, b []string) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}
