package nextcompile

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// dispatchHeader is the generated-file notice prepended to dispatch.mjs.
// Both lines are intentional: the first tells humans not to edit, the
// second gives enough generator provenance that a diff in the PR is
// immediately traceable.
const dispatchHeader = `// GENERATED BY nextcompile — DO NOT EDIT.
// Route dispatch table consumed by _nextdeploy/runtime/dispatcher.mjs.
`

// EmitDispatchTable writes the generated ESM at <outDir>/_nextdeploy/dispatch.mjs.
// The file exports five symbols the runtime imports:
//
//	staticTable    — Record<routePath, { kind, usesRSC, hasActions, load }>
//	dynamicTable   — Array<{ route, kind, pattern, paramNames, usesRSC, hasActions, load }>
//	middlewareRef  — { compiled, load } | null   (Edge-runtime middleware.ts)
//	proxyRef       — { compiled, load } | null   (Node-runtime proxy.ts, Next 15+)
//	actionLoaders  — Record<moduleID, () => Promise<any>>  for Server Actions dispatch
//
// Each `load` is an arrow returning `import("<relative path to compiled module>")`.
// Relative paths are rooted at standaloneDir (the tree the ModuleRef.CompiledPath
// values are relative to). esbuild resolves them at bundle time.
//
// actionLoaders must be emitted here (not in entry.mjs via dynamic string
// concatenation) because esbuild's tree-shaking only tracks literal import()
// calls. Hoisting action-module imports into this generated file keeps them
// visible to the bundler.
//
// usesRSC and hasActions propagate from the scanner so the runtime dispatcher
// can route a page through rsc.mjs vs the Pages-Router legacy path without
// re-scanning the compiled source at request time.
//
// standaloneDir is the path the ModuleRef.CompiledPath values are relative
// to. When outDir lives inside standaloneDir at any depth, dispatch.mjs's
// imports need to walk back out to standaloneDir before descending into
// `.next/...`. Pass empty string to get the legacy single-`../` behaviour
// (assumes dispatch.mjs ends up directly under standaloneDir).
func EmitDispatchTable(refs []ModuleRef, actions *ActionManifest, outDir, standaloneDir string) (string, error) {
	dir := filepath.Join(outDir, "_nextdeploy")
	if err := os.MkdirAll(dir, 0o750); err != nil {
		return "", fmt.Errorf("mkdir _nextdeploy: %w", err)
	}
	path := filepath.Join(dir, "dispatch.mjs")

	prefix := importPrefixFor(dir, standaloneDir)
	src := renderDispatchTable(refs, actions, prefix)

	if err := os.WriteFile(path, []byte(src), 0o640); err != nil {
		return "", fmt.Errorf("write dispatch.mjs: %w", err)
	}
	return path, nil
}

// importPrefixFor returns the path string an ESM importer at dispatchDir
// must prepend to a standaloneDir-relative path so the import resolves
// against standaloneDir.
//
// Examples:
//
//	dispatchDir="/x/_nextdeploy"        standaloneDir="/x"        → "../"
//	dispatchDir="/x/.nextdeploy-cf/_nextdeploy"  standaloneDir="/x" → "../../"
//
// On any error (paths can't be made absolute, can't compute relative)
// we fall back to "../" — the original behaviour, safe for the simple
// case and obvious if it breaks.
func importPrefixFor(dispatchDir, standaloneDir string) string {
	if standaloneDir == "" {
		return "../"
	}
	absDispatch, err := filepath.Abs(dispatchDir)
	if err != nil {
		return "../"
	}
	absStandalone, err := filepath.Abs(standaloneDir)
	if err != nil {
		return "../"
	}
	rel, err := filepath.Rel(absDispatch, absStandalone)
	if err != nil {
		return "../"
	}
	rel = filepath.ToSlash(rel)
	if rel == "." {
		return ""
	}
	return rel + "/"
}

// renderDispatchTable is the pure string-builder. Separated from the I/O
// so tests can assert on the emitted source without a tempdir.
//
// importPrefix is prepended to every standalone-relative compiledPath
// before being emitted as an import specifier. Callers who don't have a
// concrete file layout in mind should pass "../" — the legacy default
// for when dispatch.mjs lands directly under the standalone root.
func renderDispatchTable(refs []ModuleRef, actions *ActionManifest, importPrefix string) string {
	statics, dynamics, middleware, proxy := partitionRefs(refs)

	sort.Slice(statics, func(i, j int) bool { return statics[i].RoutePath < statics[j].RoutePath })
	sort.Slice(dynamics, func(i, j int) bool {
		return dynamicSpecificity(dynamics[i].RoutePath) > dynamicSpecificity(dynamics[j].RoutePath)
	})

	var b strings.Builder
	b.WriteString(dispatchHeader)
	b.WriteByte('\n')

	// Static table — flat record, O(1) lookup at runtime.
	b.WriteString("export const staticTable = Object.freeze({\n")
	for _, r := range statics {
		b.WriteString(fmt.Sprintf(
			"  %s: %s,\n",
			jsKey(r.RoutePath), renderEntryBody(r, importPrefix),
		))
	}
	b.WriteString("});\n\n")

	// Dynamic table — regex + param names + load. Ordered by specificity.
	b.WriteString("export const dynamicTable = Object.freeze([\n")
	for _, r := range dynamics {
		pattern, params := routeToRegex(r.RoutePath)
		b.WriteString(fmt.Sprintf(
			"  { route: %q, pattern: %s, paramNames: %s, %s },\n",
			r.RoutePath, pattern, paramNamesLiteral(params),
			renderEntryFields(r, importPrefix),
		))
	}
	b.WriteString("]);\n\n")

	// Middleware (edge runtime).
	writeOptionalRef(&b, "middlewareRef", middleware, importPrefix)
	// Proxy (Node runtime, Next 15+). Dispatched ahead of middleware when present.
	writeOptionalRef(&b, "proxyRef", proxy, importPrefix)

	// Action module loaders. Keyed by moduleID exactly as Next emitted it
	// (e.g. "app/actions/page"). We append ".js" so the standalone-relative
	// path lands at server/<moduleID>.js, then prefix with importPrefix
	// to reach the compiled module from dispatch.mjs.
	b.WriteString("\nexport const actionLoaders = Object.freeze({\n")
	if actions != nil && len(actions.Actions) > 0 {
		modules := uniqueActionModules(actions)
		sort.Strings(modules)
		for _, m := range modules {
			compiledPath := "server/" + m + ".js"
			b.WriteString(fmt.Sprintf(
				"  %s: () => import(%s),\n",
				jsStringLiteral(m),
				jsStringLiteral(importPath(compiledPath, importPrefix)),
			))
		}
	}
	b.WriteString("});\n")

	return b.String()
}

// uniqueActionModules returns the deduplicated list of compiled module IDs
// referenced by any action in the manifest.
func uniqueActionModules(a *ActionManifest) []string {
	seen := map[string]struct{}{}
	for _, entry := range a.Actions {
		if entry.Module == "" {
			continue
		}
		seen[entry.Module] = struct{}{}
	}
	out := make([]string, 0, len(seen))
	for m := range seen {
		out = append(out, m)
	}
	return out
}

// renderEntryBody emits the full {kind, ..., load, loadClientManifest, loadLayouts}
// object literal for a static-table entry.
func renderEntryBody(r ModuleRef, importPrefix string) string {
	return "{ " + renderEntryFields(r, importPrefix) + " }"
}

// renderEntryFields emits the field list (without surrounding braces) shared
// by static and dynamic table entries.
func renderEntryFields(r ModuleRef, importPrefix string) string {
	var parts []string
	parts = append(parts,
		fmt.Sprintf("kind: %q", string(r.Kind)),
		fmt.Sprintf("usesRSC: %t", r.UsesRSC),
		fmt.Sprintf("hasActions: %t", r.HasActions),
		fmt.Sprintf("ppr: %t", r.PPREnabled),
		fmt.Sprintf("compiled: %q", r.CompiledPath),
		fmt.Sprintf("load: () => import(%s)", jsStringLiteral(importPath(r.CompiledPath, importPrefix))),
	)
	if r.ClientManifestPath != "" {
		parts = append(parts, fmt.Sprintf(
			"loadClientManifest: () => import(%s, { with: { type: \"json\" } })",
			jsStringLiteral(importPath(r.ClientManifestPath, importPrefix)),
		))
	} else {
		parts = append(parts, "loadClientManifest: null")
	}
	if len(r.LayoutChain) > 0 {
		parts = append(parts, "loadLayouts: ["+renderLayoutLoaders(r.LayoutChain, importPrefix)+"]")
	} else {
		parts = append(parts, "loadLayouts: []")
	}
	return strings.Join(parts, ", ")
}

// renderLayoutLoaders emits the comma-separated list of arrow-import calls
// for a page's layout chain (root → leaf order).
func renderLayoutLoaders(paths []string, importPrefix string) string {
	out := make([]string, len(paths))
	for i, p := range paths {
		out[i] = fmt.Sprintf("() => import(%s)", jsStringLiteral(importPath(p, importPrefix)))
	}
	return strings.Join(out, ", ")
}

func writeOptionalRef(b *strings.Builder, name string, ref *ModuleRef, importPrefix string) {
	if ref == nil {
		b.WriteString(fmt.Sprintf("export const %s = null;\n", name))
		return
	}
	b.WriteString(fmt.Sprintf(
		"export const %s = { compiled: %q, load: () => import(%s) };\n",
		name, ref.CompiledPath, jsStringLiteral(importPath(ref.CompiledPath, importPrefix)),
	))
}

// partitionRefs splits scanned refs into static, dynamic, middleware, and
// proxy buckets. Layouts and unknowns are skipped — they're pulled in
// transitively when esbuild bundles the page/route modules they support.
func partitionRefs(refs []ModuleRef) (static, dynamic []ModuleRef, middleware, proxy *ModuleRef) {
	for i := range refs {
		r := refs[i]
		switch r.Kind {
		case RouteKindMiddleware:
			mw := r
			middleware = &mw
			continue
		case RouteKindProxy:
			px := r
			proxy = &px
			continue
		case RouteKindPage, RouteKindAPI:
			// fall through to dynamic/static partition
		default:
			continue
		}
		if isDynamicRoute(r.RoutePath) {
			dynamic = append(dynamic, r)
		} else {
			static = append(static, r)
		}
	}
	return
}

// isDynamicRoute checks if a route contains any Next.js dynamic segment.
// Patterns: [slug], [...rest], [[...optional]].
func isDynamicRoute(route string) bool {
	return strings.Contains(route, "[")
}

// dynamicSpecificity scores a route so more specific ones dispatch first.
// /users/[id]/posts (3 segments, 1 dyn) beats /users/[...rest] (2 segments
// with catch-all). Higher score = dispatched earlier.
func dynamicSpecificity(route string) int {
	parts := strings.Split(strings.Trim(route, "/"), "/")
	score := len(parts) * 10
	for _, p := range parts {
		switch {
		case strings.HasPrefix(p, "[[..."):
			score -= 5 // optional catch-all — least specific
		case strings.HasPrefix(p, "[..."):
			score -= 4 // required catch-all
		case strings.HasPrefix(p, "["):
			score -= 1 // single dynamic segment
		}
	}
	return score
}

// routeToRegex compiles a Next-style route pattern into a JS RegExp literal
// plus the ordered list of parameter names.
//
// Mapping:
//
//	/blog/[slug]            →  /^\/blog\/([^/]+)\/?$/
//	/shop/[...path]         →  /^\/shop\/(.+?)\/?$/
//	/docs/[[...slug]]       →  /^\/docs(?:\/(.+?))?\/?$/
//
// Emits the regex as a /…/ literal so the generated ESM parses without
// a `new RegExp(...)` call — cheaper at module-init time.
func routeToRegex(route string) (pattern string, paramNames []string) {
	parts := strings.Split(strings.Trim(route, "/"), "/")
	var b strings.Builder
	b.WriteString("/^")
	for _, part := range parts {
		b.WriteByte('\\')
		b.WriteByte('/')
		switch {
		case strings.HasPrefix(part, "[[...") && strings.HasSuffix(part, "]]"):
			name := part[len("[[...") : len(part)-2]
			// Rewrite to make the /segment optional as well.
			// Undo the just-written slash and emit an optional group.
			s := b.String()
			s = s[:len(s)-2] // drop \/
			b.Reset()
			b.WriteString(s)
			b.WriteString("(?:\\/(.+?))?")
			paramNames = append(paramNames, name)
		case strings.HasPrefix(part, "[...") && strings.HasSuffix(part, "]"):
			name := part[len("[...") : len(part)-1]
			b.WriteString("(.+?)")
			paramNames = append(paramNames, name)
		case strings.HasPrefix(part, "[") && strings.HasSuffix(part, "]"):
			name := part[1 : len(part)-1]
			b.WriteString("([^/]+)")
			paramNames = append(paramNames, name)
		default:
			b.WriteString(escapeRegexLiteral(part))
		}
	}
	b.WriteString("\\/?$/")
	return b.String(), paramNames
}

// escapeRegexLiteral escapes characters that are metacharacters in JS regex.
// Keep the set intentionally narrow — a route segment is already URL-valid
// so most metacharacters just don't appear.
func escapeRegexLiteral(s string) string {
	replacer := strings.NewReplacer(
		".", "\\.",
		"+", "\\+",
		"*", "\\*",
		"?", "\\?",
		"(", "\\(",
		")", "\\)",
		"$", "\\$",
		"^", "\\^",
		"|", "\\|",
	)
	return replacer.Replace(s)
}

// jsKey quotes a property key for safety — route paths contain / and [ which
// are not valid in bare keys.
func jsKey(s string) string {
	return jsStringLiteral(s)
}

// jsStringLiteral emits a double-quoted JS string literal with the minimum
// escaping needed for safe embedding in generated source.
func jsStringLiteral(s string) string {
	var b strings.Builder
	b.Grow(len(s) + 2)
	b.WriteByte('"')
	for _, r := range s {
		switch r {
		case '"':
			b.WriteString(`\"`)
		case '\\':
			b.WriteString(`\\`)
		case '\n':
			b.WriteString(`\n`)
		case '\r':
			b.WriteString(`\r`)
		default:
			b.WriteRune(r)
		}
	}
	b.WriteByte('"')
	return b.String()
}

func paramNamesLiteral(names []string) string {
	if len(names) == 0 {
		return "[]"
	}
	parts := make([]string, len(names))
	for i, n := range names {
		parts[i] = jsStringLiteral(n)
	}
	return "[" + strings.Join(parts, ", ") + "]"
}

// importPath translates a standalone-relative compiled path into the
// import specifier used inside dispatch.mjs. The prefix is computed by
// importPrefixFor based on where dispatch.mjs ends up vs. the standalone
// root the compiledPath is relative to.
func importPath(compiledPath, importPrefix string) string {
	return importPrefix + compiledPath
}
