package nextcompile

import (
	"fmt"
	"os"
	"path/filepath"
)

// entryTemplate is the esbuild entrypoint. Ties every generated artifact
// to the static runtime and exports the Worker fetch handler.
//
// JSON imports use `with { type: "json" }` — esbuild supports it on
// --format=esm out of the box.
//
// actionLoaders is built here (not Go-side) because the module IDs come
// from the action manifest, and JavaScript's dynamic import semantics
// mean each import() call site creates a distinct lazy binding. The
// simplest correct form is: a plain object mapping moduleID → () => import.
// We generate it inline from action_manifest.json at module-init time so
// the generated Go-side table stays route-only.
const entryTemplate = `// GENERATED BY nextcompile — DO NOT EDIT.
// Worker fetch entrypoint. Bundles runtime + dispatch table + manifests.
//
// actionLoaders comes from dispatch.mjs (not built here) because its
// import() calls must be literal for esbuild to tree-shake. Building it
// dynamically from a string-keyed manifest would defeat the bundler.

import { dispatch } from "./runtime/dispatcher.mjs";
import { runGuard } from "./runtime/guard.mjs";
import {
  staticTable,
  dynamicTable,
  middlewareRef,
  proxyRef,
  actionLoaders,
} from "./dispatch.mjs";
import manifest from "./manifest.json" with { type: "json" };
import actionManifest from "./action_manifest.json" with { type: "json" };
import protection from "./protection.json" with { type: "json" };

const tables = {
  manifest,
  staticTable,
  dynamicTable,
  middlewareRef,
  proxyRef,
  actionManifest,
  actionLoaders,
  // Edge protection: runGuard runs first inside dispatch(). protection is
  // null when nextdeploy.yml declares no cloudflare.protection block.
  guard: runGuard,
  protection,
};

export default {
  async fetch(request, env, ctx) {
    return dispatch(request, env, ctx, tables);
  },
};
`

// EmitWorkerEntry writes the Worker entrypoint that ties everything
// together. The output path is what the adapter feeds to esbuild.
func EmitWorkerEntry(outDir string) (string, error) {
	dir := filepath.Join(outDir, "_nextdeploy")
	if err := os.MkdirAll(dir, 0o750); err != nil {
		return "", fmt.Errorf("mkdir _nextdeploy: %w", err)
	}
	path := filepath.Join(dir, "worker_entry.mjs")
	if err := os.WriteFile(path, []byte(entryTemplate), 0o640); err != nil {
		return "", fmt.Errorf("write worker_entry.mjs: %w", err)
	}
	return path, nil
}
