[build]
# Build command with additional checks and debug information
cmd = "go build -v -gcflags='all=-N -l' -tags=debug -o ./tmp/main ."
# Enable all static analysis tools
pre_cmd = "go vet ./... && staticcheck ./... && golangci-lint run"
# Only proceed with build if pre-commands succeed
stop_on_error = true

bin = "tmp/main"
full_bin = "./tmp/main"
delay = 1000

# Exclude directories that don't need to trigger rebuilds
exclude_dir = ["vendor", "tmp", "testdata", "docs", "dist"]
include_ext = ["go", "mod", "sum"]

[build.env]
# Enable debug mode and disable optimizations
GOFLAGS = "-trimpath -ldflags='-w=false'"
CGO_ENABLED = "0"
GOOS = "linux"  # or your target OS
GOARCH = "amd64" # or your target arch

# Optional: Add debug variables
[build.args]
DEBUG = "true"
LOG_LEVEL = "debug"

# Optional: Add custom logger colors for better visibility
[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"
