
linters:
  # Disable all linters by default and enable only these
  disable-all: true
  enable:
    - gofmt
    - goimports
    - govet
    - staticcheck
    - errcheck
    - typecheck
    - unused
    - ineffassign
    - misspell

linters-settings:
  govet:
    check-shadowing: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
