package cicd

// Per-PR preview deployments.
//
// The isolation comes almost for free: every Cloudflare resource is already
// namespaced by environment (<app>-<env> for the Worker,
// nextdeploy-<app>-<env>-assets for the R2 bucket). Setting the environment to
// "pr-42" therefore yields a completely separate stack, and `destroy
// --environment pr-42` can never reach production because it operates on a
// different script entirely.
//
// Previews are Cloudflare-first. The --environment flag works for AWS/VPS at
// the config level, but the URL composition and teardown below are CF-specific.

// PreviewWorkflowPath and PreviewCleanupWorkflowPath are repo-relative.
const (
	PreviewWorkflowPath        = ".github/workflows/preview.yml"
	PreviewCleanupWorkflowPath = ".github/workflows/preview-cleanup.yml"
)

// RenderPreviewWorkflow returns the YAML that deploys a per-PR preview stack
// and comments its URL on the pull request.
//
// Requires one extra repository secret beyond the normal Cloudflare pair:
// CLOUDFLARE_WORKERS_SUBDOMAIN — the account's workers.dev subdomain (the
// <x> in https://<worker>.<x>.workers.dev). It is a stable per-account value,
// set once.
func RenderPreviewWorkflow() string {
	return `# Generated by ` + "`nextdeploy generate-ci --preview`" + ` — re-run to regenerate.
#
# Every pull request gets an isolated, live preview stack named <app>-pr-<N>,
# with its own Worker and R2 asset bucket. Closing the PR tears it down (see
# preview-cleanup.yml).
name: Preview

on:
  pull_request:
    types: [opened, synchronize, reopened]

# A rapid series of pushes should only ship the newest commit.
concurrency:
  group: preview-${{ github.event.number }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write # to comment the preview URL

jobs:
  preview:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.25'
          cache: true

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install app dependencies
        run: |
          if [ -f bun.lockb ] || [ -f bun.lock ]; then
            curl -fsSL https://bun.sh/install | bash
            echo "$HOME/.bun/bin" >> "$GITHUB_PATH"
            "$HOME/.bun/bin/bun" install --frozen-lockfile
          elif [ -f pnpm-lock.yaml ]; then
            corepack enable
            pnpm install --frozen-lockfile
          else
            npm ci
          fi

      - name: Install nextdeploy CLI (pinned)
        run: |
          go install github.com/aynaash/nextdeploy/cli@` + CLIVersion + `
          GOBIN="$(go env GOPATH)/bin"
          ln -sf "$GOBIN/cli" "$GOBIN/nextdeploy"
          echo "$GOBIN" >> "$GITHUB_PATH"

      - name: Deploy preview
        id: deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          SUBDOMAIN: ${{ secrets.CLOUDFLARE_WORKERS_SUBDOMAIN }}
        run: |
          set -o pipefail
          ENV_NAME="pr-${{ github.event.number }}"
          nextdeploy apply --environment "$ENV_NAME"
          nextdeploy ship --environment "$ENV_NAME" --no-provision --verify | tee ship.log
          WORKER=$(grep -oE 'NEXTDEPLOY_WORKER_NAME=[^[:space:]]+' ship.log | tail -1 | cut -d= -f2)
          if [ -z "$WORKER" ]; then
            echo "::error::ship did not report NEXTDEPLOY_WORKER_NAME"; exit 1
          fi
          echo "url=https://${WORKER}.${SUBDOMAIN}.workers.dev" >> "$GITHUB_OUTPUT"

      # The HTML marker lets this job UPDATE its own comment on every push
      # instead of adding one per commit.
      - name: Comment preview URL
        uses: actions/github-script@v7
        env:
          PREVIEW_URL: ${{ steps.deploy.outputs.url }}
        with:
          script: |
            const url = process.env.PREVIEW_URL;
            const marker = "<!-- nextdeploy-preview -->";
            const body = marker + "\n Preview deployed: " + url +
              "\n\n_Updated for commit " + context.sha.slice(0, 7) + "._";
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });
            const existing = comments.find((c) => c.body && c.body.includes(marker));
            if (existing) {
              await github.rest.issues.updateComment({
                owner: context.repo.owner, repo: context.repo.repo,
                comment_id: existing.id, body,
              });
            } else {
              await github.rest.issues.createComment({
                owner: context.repo.owner, repo: context.repo.repo,
                issue_number: context.issue.number, body,
              });
            }
`
}

// RenderPreviewCleanupWorkflow returns the YAML that destroys a PR's preview
// stack when the PR closes.
//
// Always pair create with destroy: without this, every PR leaks a Worker and
// an R2 bucket until the account hits its limits. The `closed` trigger fires
// for both merge and plain close, so no stack is missed.
func RenderPreviewCleanupWorkflow() string {
	return `# Generated by ` + "`nextdeploy generate-ci --preview`" + ` — re-run to regenerate.
#
# Reclaims the per-PR preview stack. Env-scoped destroy means this can only
# ever touch <app>-pr-<N>, never production.
name: Preview cleanup

on:
  pull_request:
    types: [closed]

concurrency:
  group: preview-cleanup-${{ github.event.number }}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  destroy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.25'
          cache: true

      - name: Install nextdeploy CLI (pinned)
        run: |
          go install github.com/aynaash/nextdeploy/cli@` + CLIVersion + `
          GOBIN="$(go env GOPATH)/bin"
          ln -sf "$GOBIN/cli" "$GOBIN/nextdeploy"
          echo "$GOBIN" >> "$GITHUB_PATH"

      - name: Destroy preview stack
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: nextdeploy destroy --environment "pr-${{ github.event.number }}" --yes --force
`
}
