// Package cicd renders the GitHub Actions deploy workflow. It is the single
// source of truth for both `nextdeploy generate-ci` and the scaffolder, so the
// two can never drift — previously each shipped its own file (different
// runtime, different install step, different secrets), and a user who ran both
// `init` and `generate-ci` got two workflows and two deploys per push.
package cicd

// WorkflowPath is where the rendered workflow is written, relative to the
// repository root. Both callers use it so a scaffolded app and `generate-ci`
// produce exactly one file.
const WorkflowPath = ".github/workflows/nextdeploy.yml"

// CLIVersion pins the nextdeploy CLI installed in CI. Bump on release; keep in
// sync with .release-please-manifest.json.
//
// Pinning rather than @latest is deliberate: @latest recompiles on every run
// and silently picks up breaking releases, so a deploy that worked yesterday
// can fail today with no change to the repo.
const CLIVersion = "v0.15.1"

// RenderDeployWorkflow returns the YAML for WorkflowPath.
//
// The workflow is TARGET-AWARE AT RUNTIME: a `detect` step reads nextdeploy.yml
// on the runner and runs the matching deploy (cloudflare | vps). The
// renderer therefore takes no target parameter — one file works for every
// target and keeps working when the app is retargeted, without regenerating CI.
// `generate-ci` still resolves the target, but only to print which secrets the
// user needs to set.
func RenderDeployWorkflow() string {
	return `# Generated by ` + "`nextdeploy generate-ci`" + ` — re-run to regenerate.
#
# Target-aware: push to main and the deployment matching nextdeploy.yml runs
# from the CI runner (cloudflare | vps). Retargeting the app does not
# require regenerating this file.
#
# Application secrets do NOT belong here — declare them in nextdeploy.yml so
# ` + "`secenv`" + ` folds them into every deploy, not just CI ones. Only per-target
# DEPLOY credentials are wired below.
name: deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

# Serialize deploys per branch. Never cancel in-flight: a half-applied deploy
# is worse than a superseded one.
concurrency:
  group: nextdeploy-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.25'
          cache: true

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      # Respect whichever package manager the repo actually uses.
      - name: Install app dependencies
        run: |
          if [ -f bun.lockb ] || [ -f bun.lock ]; then
            curl -fsSL https://bun.sh/install | bash
            echo "$HOME/.bun/bin" >> "$GITHUB_PATH"
            "$HOME/.bun/bin/bun" install --frozen-lockfile
          elif [ -f pnpm-lock.yaml ]; then
            corepack enable
            pnpm install --frozen-lockfile
          else
            npm ci
          fi

      # Version-pinned CLI — see cicd.CLIVersion. ` + "`go install …/cli`" + ` yields a binary
      # named ` + "`cli`" + `, so ` + "`nextdeploy`" + ` would be "command not found" without
      # the symlink below.
      - name: Install nextdeploy CLI (pinned)
        run: |
          go install github.com/aynaash/nextdeploy/cli@` + CLIVersion + `
          GOBIN="$(go env GOPATH)/bin"
          ln -sf "$GOBIN/cli" "$GOBIN/nextdeploy"
          echo "$GOBIN" >> "$GITHUB_PATH"

      # Decide the deployment type from nextdeploy.yml — the "deploy according
      # to type" step. Keeping this at runtime is what makes one file portable.
      - name: Detect deployment type
        id: detect
        run: |
          if grep -qE '^[[:space:]]*provider:[[:space:]]*cloudflare' nextdeploy.yml; then
            type=cloudflare
          elif grep -qE '^target_type:[[:space:]]*vps' nextdeploy.yml; then
            type=vps
          else
            echo "::error::Could not determine deployment type from nextdeploy.yml"; exit 1
          fi
          echo "type=$type" >> "$GITHUB_OUTPUT"
          echo "Deploying via: $type"

      # Only Cloudflare runs a separate ` + "`apply`" + `: it reconciles D1/KV/R2/
      # Vectorize before the Worker ships. VPS ships a release over SSH.
      - name: Deploy to Cloudflare
        if: steps.detect.outputs.type == 'cloudflare'
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
        run: |
          nextdeploy apply
          nextdeploy ship --no-provision --verify

      - name: Deploy to VPS
        if: steps.detect.outputs.type == 'vps'
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          nextdeploy ship --verify
`
}
