package client

import (
	"fmt"
)

func PrintUsage() {
	fmt.Println("NextDeploy Daemon - Docker Container Management")
	fmt.Println("\nUsage:")
	fmt.Println("  Start daemon: nextdeployd daemon [--config=/path/to/config.json]")
	fmt.Println("\n🚀 Daemon Management Commands:")
	fmt.Println("  nextdeployd daemon                          # Start in background (detached)")
	fmt.Println("  nextdeployd daemon --foreground            # Start in foreground for debugging")
	fmt.Println("  nextdeployd daemon --config=/path/to/config.json  # Start with custom config")
	fmt.Println("  nextdeployd status                         # Check if daemon is running")
	fmt.Println("  nextdeployd stopdaemon                     # Gracefully stop the daemon")
	fmt.Println("  nextdeployd restart                        # Restart the daemon")
	fmt.Println("  nextdeployd --version                      # Show version information")
	fmt.Println("  nextdeployd --help                         # Show general help")
	fmt.Println("\n📦 Container Lifecycle Commands:")
	fmt.Println("  nextdeployd deploy --image=nginx:latest --name=web-server")
	fmt.Println("  nextdeployd deploy --image=myapp:1.0.0 --name=api --ports=8080:3000")
	fmt.Println("  nextdeployd deploy --image=postgres:15 --name=db --env=POSTGRES_PASSWORD=secret")
	fmt.Println("  nextdeployd deploy --image=redis:7 --name=cache --volumes=/data/redis:/data")
	fmt.Println("  nextdeployd start --container=web-server")
	fmt.Println("  nextdeployd stop --container=web-server")
	fmt.Println("  nextdeployd restart --container=web-server")
	fmt.Println("  nextdeployd remove --container=web-server")
	fmt.Println("  nextdeployd remove --container=web-server --force=true")
	fmt.Println("\n🔍 Container Inspection Commands:")
	fmt.Println("  nextdeployd listcontainers                 # List running containers")
	fmt.Println("  nextdeployd listcontainers --all=true      # List all containers (including stopped)")
	fmt.Println("  nextdeployd listcontainers --format=json   # JSON output format")
	fmt.Println("  nextdeployd logs --container=web-server")
	fmt.Println("  nextdeployd logs --container=api --lines=50")
	fmt.Println("  nextdeployd logs --container=app --follow=true")
	fmt.Println("  nextdeployd logs --container=app --tail=100")
	fmt.Println("  nextdeployd inspect --container=web-server")
	fmt.Println("  nextdeployd health --container=web-server")
	fmt.Println("  nextdeployd health                         # System health check")
	fmt.Println("  nextdeployd inspect --container=db --format=json")
	fmt.Println("  nextdeployd inspect --container=api --pretty")
	fmt.Println("\n🚢 Deployment Strategy Commands:")
	fmt.Println("  nextdeployd pull --image=registry.com/app:v2.0.0 --bluegreen=true")
	fmt.Println("  nextdeployd switch --current=app-v1 --new=app:v2.0.0 --bluegreen=true")
	fmt.Println("  nextdeployd health --container=app-v2-bluegreen")
	fmt.Println("  nextdeployd pull --image=registry.com/newapp:1.0.0 --newapp=true")
	fmt.Println("  nextdeployd switch --current=none --new=newapp:1.0.0 --newapp=true")
	fmt.Println("  nextdeployd pull --image=myapp:latest")
	fmt.Println("  nextdeployd switch --current=myapp-old --new=myapp:latest")
	fmt.Println("  nextdeployd rollback --container=myapp")
	fmt.Println("  nextdeployd rollback --container=api --to=previous-version")
	fmt.Println("  nextdeployd deploy --image=app:v2.0.0 --name=app-canary --ports=8081:3000")
	fmt.Println("  nextdeployd swapcontainers --from=app-production --to=app-canary")
	fmt.Println("\n🌐 Reverse Proxy & Networking:")
	fmt.Println("  nextdeployd caddy --setup=true")
	fmt.Println("  nextdeployd caddy --config=/etc/caddy/Caddyfile")
	fmt.Println("  nextdeployd caddy --reload")
	fmt.Println("  nextdeployd ports --container=web-server --add=443:3443")
	fmt.Println("  nextdeployd ports --container=api --remove=8080")
	fmt.Println("  nextdeployd ports --list --container=app")
	fmt.Println("  nextdeployd network --create=app-network")
	fmt.Println("  nextdeployd network --connect=web-server --network=app-network")
	fmt.Println("  nextdeployd network --disconnect=db --network=app-network")
	fmt.Println("\n📊 Monitoring & Maintenance Commands:")
	fmt.Println("  nextdeployd stats                          # Container resource usage")
	fmt.Println("  nextdeployd stats --container=web-server   # Specific container stats")
	fmt.Println("  nextdeployd stats --all --format=json      # All containers in JSON")
	fmt.Println("  nextdeployd top                            # Live container processes")
	fmt.Println("  nextdeployd top --container=api")
	fmt.Println("  nextdeployd events                         # Real-time Docker events")
	fmt.Println("  nextdeployd cleanup --images               # Remove unused images")
	fmt.Println("  nextdeployd cleanup --containers           # Remove stopped containers")
	fmt.Println("  nextdeployd cleanup --volumes              # Remove unused volumes")
	fmt.Println("  nextdeployd cleanup --all                  # Full cleanup")
	fmt.Println("  nextdeployd backup --container=db --output=backup.tar")
	fmt.Println("  nextdeployd restore --container=db --input=backup.tar")
	fmt.Println("\n🔐 Registry & Image Management:")
	fmt.Println("  nextdeployd pull --image=nginx:latest")
	fmt.Println("  nextdeployd pull --image=registry.com/app:1.0.0 --auth=true")
	fmt.Println("  nextdeployd images                         # List local images")
	fmt.Println("  nextdeployd images --prune                 # Remove unused images")
	fmt.Println("  nextdeployd registry --login --url=registry.com --user=user --token=token")
	fmt.Println("  nextdeployd registry --logout")
	fmt.Println("  nextdeployd registry --list")
	fmt.Println("  nextdeployd tag --image=app:latest --target=app:production")
	fmt.Println("  nextdeployd tag --image=app:v1.0.0 --target=registry.com/app:1.0.0")
	fmt.Println("\n⚙️ Configuration Management:")
	fmt.Println("  nextdeployd config --show                  # Show current configuration")
	fmt.Println("  nextdeployd config --set log_level=debug   # Set configuration value")
	fmt.Println("  nextdeployd config --get socket_path       # Get specific config value")
	fmt.Println("  nextdeployd config --reload                # Reload configuration")
	fmt.Println("  nextdeployd env --container=app --list     # List environment variables")
	fmt.Println("  nextdeployd env --container=api --set=DEBUG=true")
	fmt.Println("  nextdeployd env --container=web --unset=OLD_VAR")
	fmt.Println("  nextdeployd volume --create=app-data")
	fmt.Println("  nextdeployd volume --list")
	fmt.Println("  nextdeployd volume --remove=temp-data")
	fmt.Println("\n🛠️ Advanced Operations:")
	fmt.Println("  nextdeployd exec --container=web-server --command=\"bash\"")
	fmt.Println("  nextdeployd exec --container=db --command=\"psql -U user dbname\"")
	fmt.Println("  nextdeployd cp --container=app --src=/app/logs/app.log --dest=./app.log")
	fmt.Println("  nextdeployd cp --container=db --src=./backup.sql --dest=/tmp/backup.sql")
	fmt.Println("  nextdeployd update --container=web-server --image=nginx:1.25")
	fmt.Println("  nextdeployd update --container=api --memory=512m --cpus=1")
	fmt.Println("  nextdeployd scale --container=app --replicas=3")
	fmt.Println("  nextdeployd scale --container=api --max=5 --min=2")
	fmt.Println("\n📋 Command Options Reference:")
	fmt.Println("  Common Flags:")
	fmt.Println("    --config=path    # Custom config file")
	fmt.Println("    --format=json|table # Output format")
	fmt.Println("    --verbose        # Detailed output")
	fmt.Println("    --quiet          # Minimal output")
	fmt.Println("    --force          # Force operation")
	fmt.Println("  Deployment Options:")
	fmt.Println("    --ports          # Port mappings (80:3000)")
	fmt.Println("    --env            # Environment variables")
	fmt.Println("    --volumes        # Volume mounts")
	fmt.Println("    --restart        # Restart policy")
	fmt.Println("    --memory         # Memory limit")
	fmt.Println("    --cpus           # CPU limit")
	fmt.Println("  Filtering Options:")
	fmt.Println("    --all            # Include stopped containers")
	fmt.Println("    --filter         # Filter results")
	fmt.Println("    --tail           # Number of log lines")
	fmt.Println("    --follow         # Follow log output")
	fmt.Println("\nFor detailed help on a specific command, use:")
	fmt.Println("  nextdeployd <command> --help")

}
