// nextcompile runtime — request-time dispatcher.
//
// Bundled into every deployed Worker. Reads the build-time manifest +
// dispatch table (generated by nextcompile Go-side) and routes incoming
// requests to the right compiled Next.js module.
//
// Dispatch order (first match wins):
//   1. proxy.ts (Next 15+, Node runtime) — if declared, runs first
//   2. middleware.ts (Edge runtime) — if declared, runs if proxy didn't
//   3. Static assets (/_next/static/*, /public/*) — served from R2
//   4. Static route table — exact path match
//   5. SSG routes — pre-rendered HTML from R2
//   6. ISR routes — HTML from R2 (revalidation arrives with cache.mjs)
//   7. Dynamic table — regex-matched routes, ordered by specificity
//   8. Root-served public files (/install.sh, /robots.txt, …) from R2
//   9. 404
//
// Every handler invocation is wrapped in an AsyncLocalStorage context so
// Next's async cookies() / headers() / draftMode() resolve to per-request
// values. See context.mjs.
//
// Pages with manifest-declared usesRSC=true route through rsc.mjs, which
// delegates to the vendored react-server-dom-webpack bundle. Pages
// without RSC fall through to the legacy default-export path (Pages
// Router + simple App Router pages).

import { serveStaticFromR2, serveSSGFromR2, serveRootPublicFromR2 } from "./serve.mjs";
import { matchDynamic, buildRouteContext } from "./route_match.mjs";
import { notFound, serverError } from "./errors.mjs";
import { runWithContext, createRequestContext } from "./context.mjs";
import { renderRSC } from "./rsc.mjs";
import { isServerAction, handleServerAction } from "./actions.mjs";
import { initCacheIndex, isStale } from "./cache.mjs";
import { handleImageRequest } from "./image.mjs";

// Manifest-driven cache index init. Runs at module eval; dispatcher
// invocations that follow see the populated tag→paths map. The manifest
// is passed each call to dispatch() (since worker_entry.mjs holds it),
// but the cache index needs it ahead of the first request.
let cacheIndexInitialized = false;

/**
 * @param {Request} request
 * @param {Record<string, any>} env   Cloudflare Worker bindings.
 * @param {{ waitUntil: (p: Promise<any>) => void }} ctx
 * @param {{ manifest, staticTable, dynamicTable, middlewareRef, proxyRef,
 *          actionManifest, actionLoaders }} tables
 * @returns {Promise<Response>}
 */
export async function dispatch(request, env, ctx, tables) {
  const { manifest } = tables;
  ensureCacheIndexInit(manifest);

  const url = new URL(request.url);
  const pathname = stripBasePath(url.pathname, manifest.basePath);

  // Expose the full binding set (KV, D1, R2, AI, secrets) to user proxy.ts /
  // app code that can't import runtime internals at next-build time. Read it
  // via globalThis.__nextdeployEnv (the scaffold ships a typed getEnv() helper).
  globalThis.__nextdeployEnv = env;

  try {
    // Protection guard runs before everything else (IP / rate-limit / auth),
    // ahead of static assets, short-circuits, and the user middleware stack.
    // No-op when protection.json is null.
    if (tables.guard && tables.protection) {
      const blocked = await tables.guard(request, env, ctx, tables.protection);
      if (blocked) return blocked;
    }

    const short = await tryShortCircuits(request, env, ctx, pathname, tables);
    if (short) return short;

    // Middleware / proxy may rewrite the request. Thread the (possibly
    // new) request back into subsequent stages.
    const mw = await runMiddlewareStack(request, env, ctx, tables);
    if (mw.response) return mw.response;
    request = mw.request;

    const staticRes = await tryStaticAsset(env, pathname);
    if (staticRes) return staticRes;

    const routed = await tryRouteDispatch(request, env, ctx, url, pathname, tables);
    if (routed) return routed;

    const publicRoot = await serveRootPublicFromR2(env, pathname, manifest);
    if (publicRoot) return publicRoot;

    return notFound();
  } catch (err) {
    return serverError(err);
  }
}

function ensureCacheIndexInit(manifest) {
  if (cacheIndexInitialized) return;
  initCacheIndex(manifest.isr);
  cacheIndexInitialized = true;
}

/**
 * Pre-middleware short-circuits: the /_next/image endpoint and Server
 * Action POSTs. Matches Next's dispatch priority — these must run before
 * middleware or proxy can intercept them.
 */
async function tryShortCircuits(request, env, ctx, pathname, tables) {
  if (pathname === "/_next/image" || pathname.startsWith("/_next/image?")) {
    return handleImageRequest(request, env, tables.manifest);
  }
  if (tables.actionManifest && isServerAction(request)) {
    return handleServerAction(request, env, ctx, tables.actionManifest, tables.actionLoaders);
  }
  return null;
}

/**
 * Run proxy.ts then middleware.ts. Either may short-circuit with a
 * Response or mutate the request. Returns { response?, request }.
 */
async function runMiddlewareStack(request, env, ctx, tables) {
  for (const ref of [tables.proxyRef, tables.middlewareRef]) {
    if (!ref) continue;
    const result = await runMiddlewareLike(ref, request, env, ctx);
    if (result instanceof Response) return { response: result, request };
    if (result?.request) request = result.request;
  }
  return { response: null, request };
}

/**
 * Serve /_next/static/* and /public/* straight from R2. Returns the
 * Response on hit (including the 404 when a prefixed path isn't in R2),
 * or null when the path isn't in a static prefix.
 */
async function tryStaticAsset(env, pathname) {
  if (!pathname.startsWith("/_next/static/") && !pathname.startsWith("/public/")) {
    return null;
  }
  const res = await serveStaticFromR2(env, pathname);
  return res || notFound();
}

/**
 * Run route dispatch in priority order: static table → SSG → ISR →
 * dynamic table. Returns Response on match, null to fall through.
 */
async function tryRouteDispatch(request, env, ctx, url, pathname, tables) {
  // Cached prerendered HTML (SSG / ISR) is checked FIRST. App Router
  // pages have a compiled module in staticTable AND a prerendered HTML
  // file in R2 — but the compiled module can't be invoked directly
  // (no default export, App Router runtime not available). Serving the
  // HTML from R2 is correct for any route that prerendered, regardless
  // of whether a compiled module also exists.
  const cached = await tryCachedRender(env, tables.manifest, pathname);
  if (cached) return cached;

  const staticEntry = tables.staticTable[pathname];
  if (staticEntry) {
    return invokeCompiled(staticEntry, request, env, ctx, { params: {} }, url);
  }

  const dyn = matchDynamic(pathname, tables.dynamicTable);
  if (dyn) {
    const routeCtx = buildRouteContext(url, dyn.params);
    return invokeCompiled(dyn.entry, request, env, ctx, routeCtx, url);
  }
  return null;
}

/**
 * Serve the pre-rendered HTML for SSG / ISR routes when the path isn't
 * marked stale. Unified because both tiers use the same R2 lookup path
 * and stale-check; only the manifest source differs.
 */
async function tryCachedRender(env, manifest, pathname) {
  for (const bucket of ["ssg", "isr"]) {
    const target = manifest.routes[bucket]?.[pathname];
    if (!target) continue;
    const stale = await isStale(pathname, isrTagsFor(pathname, manifest), env);
    if (stale) continue;
    const res = await serveSSGFromR2(env, target);
    if (res) return res;
  }
  return null;
}

/**
 * Import the compiled module and invoke it. Entry.kind + entry.usesRSC
 * drive which handler we use; context.mjs wraps everything.
 */
async function invokeCompiled(entry, request, env, ctx, routeCtx, url) {
  switch (entry.kind) {
    case "api": {
      const mod = await entry.load();
      return await invokeAPI(mod, request, env, ctx, routeCtx, url);
    }
    case "page":
      // RSC-tagged pages go through the Server Components renderer.
      // renderRSC now takes the whole entry so it can access layouts,
      // client manifest, and PPR flag without re-loading the module.
      if (entry.usesRSC) {
        return await renderRSC(entry, request, env, ctx, routeCtx);
      }
      // Legacy default-export path for Pages Router apps.
      {
        const mod = await entry.load();
        return await invokeLegacyPage(mod, request, env, ctx, routeCtx, url);
      }
    default:
      return notFound();
  }
}

/**
 * Route handlers (App Router route.js, Pages Router pages/api/*.js).
 * App Router: named method exports (GET/POST/PUT/DELETE/PATCH/HEAD/OPTIONS).
 * Pages Router: default export.
 *
 * Wrapped in context so handlers that call cookies()/headers() work.
 */
async function invokeAPI(mod, request, env, ctx, routeCtx, url) {
  const method = request.method.toUpperCase();
  const handler = mod[method] || mod.default;
  if (typeof handler !== "function") {
    return new Response("Method Not Allowed", { status: 405 });
  }

  pushEnvIntoProcess(env);
  const reqCtx = createRequestContext(request, env, url, routeCtx.params, ctx);

  return runWithContext(reqCtx, async () => {
    const result = await handler(request, { params: routeCtx.params || {} });
    return coerceToResponse(result, reqCtx);
  });
}

/**
 * Legacy page invocation — default-exported handler returning Response |
 * string | data. Covers Pages Router and the simplest App Router apps.
 *
 * Real App Router rendering lives in rsc.mjs; this path is the safety net
 * for apps that haven't adopted Server Components.
 */
async function invokeLegacyPage(mod, request, env, ctx, routeCtx, url) {
  const handler = mod.default || mod.handler;
  if (typeof handler !== "function") {
    return new Response(
      "nextcompile: page module has no default export and is not RSC-tagged.\n" +
        "If this is a Server Components page, ensure the scanner detected usesRSC.\n" +
        "If this is a Pages Router page, confirm the build produced a default export.",
      { status: 500 },
    );
  }

  pushEnvIntoProcess(env);
  const reqCtx = createRequestContext(request, env, url, routeCtx.params, ctx);

  return runWithContext(reqCtx, async () => {
    const result = await handler(request, { params: routeCtx.params || {} });
    return coerceToResponse(result, reqCtx);
  });
}

/**
 * Run a middleware-like module (middleware.ts OR proxy.ts). They share
 * the same return contract:
 *   - Response   → short-circuit
 *   - undefined  → continue
 *   - { request } → continue with a mutated request
 */
async function runMiddlewareLike(ref, request, env, ctx) {
  const mod = await ref.load();
  const handler = mod.default || mod.middleware || mod.proxy;
  if (typeof handler !== "function") return null;

  pushEnvIntoProcess(env);
  const url = new URL(request.url);
  const reqCtx = createRequestContext(request, env, url, {}, ctx);
  const event = { waitUntil: (p) => ctx.waitUntil(p) };

  return runWithContext(reqCtx, async () => handler(request, event));
}

/**
 * Coerce a handler's return value into a Response while applying any
 * cookies/headers the handler set via the ALS context.
 */
function coerceToResponse(result, reqCtx) {
  let response;
  if (result instanceof Response) {
    response = result;
  } else if (result === undefined || result === null) {
    response = new Response(null, { status: 204 });
  } else if (typeof result === "string") {
    response = new Response(result, {
      status: 200,
      headers: { "content-type": "text/html; charset=utf-8" },
    });
  } else {
    response = Response.json(result);
  }

  // Merge ALS-captured cookies/headers into the final response.
  if (reqCtx.setCookies.length > 0 || [...reqCtx.responseHeaders.keys()].length > 0) {
    const merged = new Headers(response.headers);
    for (const [k, v] of reqCtx.responseHeaders) merged.set(k, v);
    for (const cookie of reqCtx.setCookies) merged.append("set-cookie", cookie);
    return new Response(response.body, {
      status: response.status,
      statusText: response.statusText,
      headers: merged,
    });
  }
  return response;
}

/**
 * Mirror Worker env bindings into globalThis.process.env so Next-compiled
 * code that reads process.env.X finds its secrets. Done lazily per request
 * rather than at module init because process may not exist until the first
 * request on nodejs_compat_v2.
 */
function pushEnvIntoProcess(env) {
  if (typeof globalThis.process === "undefined") {
    globalThis.process = { env: {} };
  }
  for (const key of Object.keys(env)) {
    const val = env[key];
    if (typeof val === "string" && globalThis.process.env[key] === undefined) {
      globalThis.process.env[key] = val;
    }
  }
}

/**
 * isrTagsFor returns the tag list the manifest associated with the given
 * path. Used by isStale to consult tag-based invalidation without the
 * caller having to thread the tag index through.
 */
function isrTagsFor(pathname, manifest) {
  const tags = [];
  const tagMap = manifest?.isr?.tags;
  if (!tagMap) return tags;
  for (const [tag, paths] of Object.entries(tagMap)) {
    if (Array.isArray(paths) && paths.includes(pathname)) tags.push(tag);
  }
  return tags;
}

function stripBasePath(pathname, basePath) {
  if (!basePath) return pathname;
  if (pathname === basePath) return "/";
  if (pathname.startsWith(basePath + "/")) return pathname.slice(basePath.length);
  return pathname;
}
