name: Pull Request Validation
on:
  pull_request:
    branches: [develop, main]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      
      # Quality Gates
      - name: Lint
        run: golangci-lint run
      
      - name: Test
        run: go test -v -race -coverprofile=coverage.out ./...
      
      - name: Coverage Check
        run: |
          coverage=$(go tool cover -func=coverage.out | grep total | awk '{print substr($3, 1, length($3)-1)}')
          if (( $(echo "$coverage < 80" | bc -l) )); then
            echo "Coverage $coverage% is below 80%"
            exit 1
          fi
      
      # Security Scanning
      - name: Security Scan
        uses: cosmos/gosec-action@v2
        with:
          args: ./...
